DIMENSION = 5
FREE = 0
PLAYER_1 = 1
PLAYER_2 = 2
ROW = 0
COL = 1
RANDOM = 'random'
TRAIN = 'train'
WIN = 'win'
LOST = 'lost'
TIE = 'tie'
MU = 0.001
W0 = 0.2 # Quantity of conexions P1
W1 = 0.2 # Quantity of aligments P1
W2 = -0.2 # Quantity of islands P1
W3 = -0.2 # Quantity of conexions P2
W4 = -0.2 # Quantity of aligments P2
W5 = 0.2 # Quantity of islands P2
W6 = 0.2 # Independient term
