DIMENSION = 5
FREE = 0
PLAYER_1 = 1
PLAYER_2 = 2
ROW = 0
COL = 1
RANDOM = 'random'
TRAIN = 'train'
MU = 0.3
W0 = 0.2 # Independient term
W1 = -0.2 # Quantity of conexions
W2 = 0.2 # Quantity of algiments
W3 = 0.2 # Quantity of islands
W4 = 0.2 # Quantity of oponent conexions
W5 = -0.2 # Quantity of oponent algiments
W6 = -0.2 # Quantity of oponent islands